site_name: 2928 Wiki
site_url: https://skweston123.github.io/2928wiki/
theme:
  name: material
  logo: assets/logo.png
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.tracking

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Hardware and COTS:
    - Motors: Hardware and COTS/Motors.md
    - Fasteners: Hardware and COTS/Fasteners.md
    - Shafts and Axles: Hardware and COTS/Shafts and Axles.md
    - Bearings: Hardware and COTS/Bearings.md
    - Swerve: Hardware and COTS/Swerve.md 
  - Power Transmission:
    - Gears: Power Transmission/Gears.md
    - Belts and Pulleys: Power Transmission/Belts and Pulleys.md
    - Chain: Power Transmission/Chain.md
  - Onshape (CAD):
    - Intro to Onshape: Onshape (CAD)/Intro to Onshape.md
    - Document Structure: Onshape (CAD)/Document Structure.md
    - Block CAD: Onshape (CAD)/Block CAD.md
    - CAD for Prototypes: Onshape (CAD)/CAD for Prototypes.md
    - Versioning Best Practices: Onshape (CAD)/Versioning Best Practices.md
    - Release to Manufacture Workflow: Onshape (CAD)/Release to Manufacture Workflow.md
  - Fusion (CAM):
    - Intro to Fusion: Fusion (CAM)/Intro to Fusion.md
    - CAM Workflow: Fusion (CAM)/CAM Workflow.md
  - Design Standards:
    - Drivetrain: Design Standards/Drivetrain.md
    - Structure: Design Standards/Structure.md
    - Roller: Design Standards/Roller.md
    - Pivot: Design Standards/Pivot.md
    - Elevator: Design Standards/Elevator.md
    - Gearbox: Design Standards/Gearbox.md 
  - Manufacturing:
    - Manual Machines: Manufacturing/Manual Machines.md
    - CNC Machines: Manufacturing/CNC Machines.md
    - Hand Tools: Manufacturing/Hand Tools.md

watch:
  - docs
  - mkdocs.yml